try:
    f1=open("d:\\testfile1.txt","r+")
    f2=open("d:\\testfile.txt","w+",)
    line1=f1.read()
    line2=f2.read()
    f2.write(line1.replace('\"','\\\"'))
    print("File contents are:")
    print(line1)
    print("Modified file content stored in other file:")
    f2=open("d:\\testfile.txt","r+",)
    line=f2.read()
    print(line)
    f1.close()
    f2.close()
    f2.close()
except FileNotFoundError:
    print("File not found, cannot be opened")
