leaveprogram=""
print("This is a dice rolling program")
print("Press Enter to roll")
while leaveprogram!="q":
    import random
    input()
    n=random.randint(1,6)
    if(n==1):
        print("[-----------]")
        print("[           ]")
        print("[     o     ]")
        print("[           ]")
        print("[-----------]")
        print("Press q to quit")
        print("press enter 2 times to roll the dice again")
        leaveprogram=input()
    if(n==2):
        print("[-----------]")
        print("[           ]")
        print("[  o    o   ]")
        print("[           ]")
        print("[-----------]")
        print("Press q to quit")
        print("press enter 2 times to roll the dice again")
        leaveprogram=input()
    if(n==3):
        print("[-----------]")
        print("[          o]")
        print("[     o     ]")
        print("[o          ]")
        print("[-----------]")
        print("Press q to quit")
        print("press enter 2 times to roll the dice again")
        leaveprogram=input()
    if(n==4):
        print("[-----------]")
        print("[  o      o ]")
        print("[           ]")
        print("[  o      o ]")
        print("[-----------]")
        print("Press q to quit")
        print("press enter 2 times to roll the dice again")
        leaveprogram=input()
    if(n==5):
        print("[-----------]")
        print("[  o      o ]")
        print("[     o     ]")
        print("[  o      o ]")
        print("[-----------]")
        print("Press q to quit")
        print("press enter 2 times to roll the dice again")
        leaveprogram=input()
    if(n==6):
        print("[-----------]")
        print("[  o      o ]")
        print("[  o      o ]")
        print("[  o      o ]")
        print("[-----------]")
        print("Press q to quit")
        print("press enter 2 times to roll the dice again")
        leaveprogram=input()
